### ISSUE TITLE
Sınıf isimlerini türkçeleştirme hk.

### ISSUE THREAD

**Issue by trepcan** [iz7iz7iz/eKDG.css#2]
Sınıf isimlerini türkçeleştirmek yerine İngilizce hazırlamak ve türkçe comment eklemek iş yükü açısından çok daha uygun olacaktır düşüncesindeyim. Kullanıcıların büyük bir kısmı sınıfları copy&paste şeklinde kullandığı için açıklamalara bakarak kolaylıkla yapmak istediği işe uygun sınıf bulacaktır. Her halukarda zaten açıklama olacak sınıflar için.

**Comment by iz7iz7iz** [comment]
güzel fikir gerçekten, kolaylıkla gerçekleştirilebilir.
sınıfları ingilizce olarak öğrenmiş olanlarda yeniden öğrenmek zorunda kalmaz.
